# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CUSP_progress.py
# Created on: 2019-08-27 14:31:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CUSP_progress <csvName> <CUSP> <v70KShoreline> <csvPath> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
csvName = arcpy.GetParameterAsText(0)

CUSP = arcpy.GetParameterAsText(1)

v70KShoreline = arcpy.GetParameterAsText(2)

csvPath = arcpy.GetParameterAsText(3)

# Local variables:
v70KSLByState = ""
Value = "1"
ShorelineByState = ""
output_feature_class_Pnt = ShorelineByState
Output_Feature_Class = ""
Buffers = ""
Clipped70K = "C:\\Users\\chenglin.gan\\Documents\\ArcGIS\\Default.gdb\\Whole_US_Clip"
v70KClippedLeng = "C:\\Users\\chenglin.gan\\Documents\\ArcGIS\\Default.gdb\\Whole_US_Clip_Statistics"
ClippedLength = v70KClippedLeng
Final_Text_File = ClippedLength
Row_Count = "10930"
v70KStateLeng = ""
StateLength = v70KStateLeng
Delete_succeeded = "false"

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(v70KShoreline, "State #;NOAA_REGIO #", "false")

# Process: Select
arcpy.Select_analysis(CUSP, ShorelineByState, "\"FIPS_ALPHA\"=SUBSTRING('%Value%' FROM 1 FOR 2) AND \"NOAA_REGIO\" =SUBSTRING('%Value%' FROM 4 FOR (CHAR_LENGTH('%Value%')-3))")

# Process: Simplify Line
arcpy.SimplifyLine_cartography(ShorelineByState, Output_Feature_Class, "POINT_REMOVE", "0.5 Kilometers", "FLAG_ERRORS", "KEEP_COLLAPSED_POINTS", "CHECK", "")

# Process: Buffer
arcpy.Buffer_analysis(Output_Feature_Class, Buffers, "1 Kilometers", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Clip
arcpy.Clip_analysis(v70KSLByState, Buffers, Clipped70K, "")

# Process: Summary Statistics
arcpy.Statistics_analysis(Clipped70K, v70KClippedLeng, "Shape_Length SUM", "")

# Process: Get Field Value
arcpy.GetFieldValue_mb(v70KClippedLeng, "SUM_Shape_Length", "Double", "0")

# Process: Get Count
arcpy.GetCount_management(ShorelineByState)

# Process: Summary Statistics (2)
arcpy.Statistics_analysis(v70KSLByState, v70KStateLeng, "Shape_Length SUM", "")

# Process: Get Field Value (2)
arcpy.GetFieldValue_mb(v70KStateLeng, "SUM_Shape_Length", "Double", "0")

# Process: Calculate Value
arcpy.CalculateValue_management("calculatePercentage(r\"%csvPath%\",\"%csvName%\",\"%Value%\",%ClippedLength%,%StateLength%)", "import os, csv\\n\\ndef calculatePercentage(csvPath, csvName, location, clippedLeng, stateLeng):\\n    ext = 'txt' # Define output file extension (e.g. csv or txt)\\n    header = ['stateName','noaaRegion','ClippedLeng', 'StateLeng', 'Percentage;'] # Define header row (column names)\\n    stateName=location.split('_')[0]\\n    noaaRegion=location.split('_')[1]\\n    # Join CSV file path and name, adding extension if necessary\\n    csvfile = os.path.join(csvPath, os.extsep.join((csvName, ext)) if not os.path.splitext(csvName)[1].lower().endswith(ext) else csvName)\\n\\n    percentage = clippedLeng/stateLeng\\n\\n    hasHeader=0\\n\\n    if os.path.exists(csvfile):\\n        readFile = open(csvfile);\\n        if 'stateName,noaaRegion,ClippedLeng,StateLeng,Percentage;' in readFile.read():\\n            hasHeader=1\\n        readFile.close()\\n    \\n    # Open text file for writing\\n    with open(csvfile, 'a+') as f:\\n        w = csv.writer(f)\\n        if hasHeader==0:\\n            w.writerow(header) # Write header row\\n        row = [stateName,noaaRegion,str(clippedLeng),str(stateLeng),str(percentage)+';']\\n        w.writerow(row)\\n\\n    return csvfile", "Text File")

# Process: Delete
arcpy.Delete_management(output_feature_class_Pnt, "")

